version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t vibhab4/quiz-app:latest .
            docker tag vibhab4/quiz-app:latest vibhab4/quiz-app:v1.0.0
      - run:
          name: Push Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push vibhab4/quiz-app:latest
            docker push vibhab4/quiz-app:v1.0.0

  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_REGION
            eb init -p docker quiz-app --region $AWS_REGION
            eb deploy quiz-app-env

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
