name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies and run tests
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pytest

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/quiz-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/quiz-app:latest

      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_HOST }} ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQE..." >> ~/.ssh/known_hosts
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Debug SSH Key
        run: |
          echo "Private key:"
          echo "${{ secrets.AWS_PRIVATE_KEY }}"
          echo "${{ secrets.AWS_PRIVATE_KEY }}" | tr -d '\r' > private_key.pem
          chmod 600 private_key.pem
          ls -l private_key.pem
          cat private_key.pem
          ssh -i private_key.pem -vvv ec2-user@${{ secrets.AWS_EC2_HOST }} exit

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            echo "Connected successfully!"
            docker pull ${{ secrets.DOCKER_USERNAME }}/quiz-app:latest
            docker stop quiz-app || true
            docker rm quiz-app || true
            docker run -d -p 80:5000 --name quiz-app ${{ secrets.DOCKER_USERNAME }}/quiz-app:latest
